name: Auto Upload Template

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6 AM UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run automation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GUMROAD_EMAIL: ${{ secrets.GUMROAD_EMAIL }}
          GUMROAD_PASSWORD: ${{ secrets.GUMROAD_PASSWORD }}
        run: |
          python main.py
